
DROP TABLE IF EXISTS employees, employees_info,department,role,employees_roles;
CREATE TABLE employees(
	`UID` VARCHAR(36) NOT NULL,
	`EMP_NO` VARCHAR(64) NOT NULL,
	`MAIL` VARCHAR(255) NOT NULL,
	PRIMARY KEY (`UID`,`EMP_NO`)
	
)
ENGINE=Aria
CHARACTER SET 'utf8' 
COLLATE 'utf8_general_ci';

CREATE TABLE employees_info(
	`UID` VARCHAR(36) NOT NULL,
	`FIRST_NAME` VARCHAR(64),
	`MID_NAME` VARCHAR(64),
	`LAST_NAME` VARCHAR(64),
	`BIRTH_DATE` DATE,
	`GENDER` ENUM('M','F'),
	`CONTACT_ADDR_1` VARCHAR(255),
	`CONTACT_ADDR_2` VARCHAR(255),
	`CONTACT_PHONE_1` VARCHAR(64),
	`CONTACT_PHONE_2` VARCHAR(64),
	`HIRE_DATE` DATE,
	`LEAVE_DATE` DATE,
	PRIMARY KEY(`UID`),
	FOREIGN KEY(`UID`) REFERENCES employees (UID)
)ENGINE=Aria
CHARACTER SET 'utf8' 
COLLATE 'utf8_general_ci';

CREATE TABLE department (
	`DEP_ID` VARCHAR(36) NOT NULL,
	`DEP_NO` VARCHAR(64) NOT NULL,
	`NAME` VARCHAR(64) NOT NULL,
	`REGION` VARCHAR(64) NOT NULL,
	`PARENT_DID` VARCHAR(36),
	PRIMARY KEY(`DEP_ID`,`DEP_NO`)
)ENGINE=Aria
CHARACTER SET 'utf8' 
COLLATE 'utf8_general_ci';

CREATE TABLE role(
	`DEP_ID` VARCHAR(36) NOT NULL,
	`ROLE_ID` VARCHAR(36) NOT NULL,
	`ROLE_NAME` VARCHAR(64) NOT NULL,
	`ROLE_LEVEL` INT NOT NULL,
	PRIMARY KEY (`DEP_ID`,`ROLE_ID`),
	FOREIGN KEY(DEP_ID) REFERENCES department (DEP_ID)
)ENGINE=Aria
CHARACTER SET 'utf8' 
COLLATE 'utf8_general_ci';

CREATE TABLE employees_roles (
	`UID` VARCHAR(36) NOT NULL,
	`ROLE_ID` VARCHAR(36) NOT NULL,
	`FROM_DATE` DATE NOT NULL,
	`TO_DATE` DATE,
	PRIMARY KEY(`UID`,`ROLE_ID`),
	FOREIGN KEY(`UID`) REFERENCES employees (UID),
	FOREIGN KEY(`ROLE_ID`) REFERENCES role (`ROLE_ID`)
)ENGINE=Aria
CHARACTER SET 'utf8' 
COLLATE 'utf8_general_ci';